name: Generate Checkstyle Report

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-${{ github.sha }}

      - name: Set up JDK ${{ inputs.configuration.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.configuration.java_version }}
          distribution: ${{ inputs.configuration.java_distribution }}
          cache: ${{ inputs.configuration.java_cache }}

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/reports/
