name: Generate Checkstyle Report

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-${{ github.sha }}

      - name: Extract Environment
        id: environment
        uses: actions/github-script@v6
        with:
          script: |
            const environment = '${{ inputs.configuration }}';
            console.log("Environment: " + environment);
            try {
              const parsed = JSON.parse(environment);
              console.log('Parsed: ' + parsed);
              for(let key in parsed) {
                if (parsed.hasOwnProperty(key)) {
                  console.log(key + ': ' + parsed[key]);
                  core.exportVariable(key, parsed[key]);
                }
              }
            } catch (error) {
              console.error("Error parsing JSON:", error);
              core.setFailed(error.message);
            }


      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java_version }}
          distribution: ${{ env.java_distribution }}
          cache: ${{ env.java_cache }}

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/reports/
