name: Component Tests

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    outputs:
      test-result:
        description: "Result of Component Testing"
        value: ${{ jobs.test.outputs.outcome }}


jobs:
  component_tests:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.status.outcome}}

    steps:
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-${{ github.sha }}

      - name: Set up JDK ${{ inputs.configuration.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.configuration.java_version }}
          distribution: ${{ inputs.configuration.java_distribution }}
          cache: ${{ inputs.configuration.java_cache }}

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test output
        run: echo ${{ steps.deserialize.outputs.skip }}

      - name: Run component tests
        if: ${{ inputs.configuration.component_tests != false }}
        run: |
          echo 
          echo "Running component tests..."
          mvn verify

      - name: Set status
        id: status
        run: echo "outcome=true" >> $GITHUB_OUTPUT
