name: Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      configuration:
        required: true
        type: string

permissions:
  contents: write
  deployments: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Candidate
        uses: actions/download-artifact@v4
        with:
          name: release-candidate-jar
          path: target/

      - name: Extract Environment
        id: environment
        uses: actions/github-script@v6
        with:
          script: |
            const environment = '${{ inputs.configuration }}';
            console.log("Environment: " + environment);
            try {
              const parsed = JSON.parse(environment);
              console.log('Parsed: ' + parsed);
              for(let key in parsed) {
                if (parsed.hasOwnProperty(key)) {
                  console.log(key + ': ' + parsed[key]);
                  core.exportVariable(key, parsed[key]);
                }
              }
            } catch (error) {
              console.error("Error parsing JSON:", error);
              core.setFailed(error.message);
            }

      - name: Create GitHub Release
        if: ${{ env.create_release != false }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          body: "Automated release for commit ${{ github.sha }}"

      - name: Upload release artifact
        uses: actions/upload-release-asset@v1
        if: ${{ env.create_release != false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/${{ env.PROJECT_NAME }}-${{inputs.version}}.jar
          asset_name: ${{ env.PROJECT_NAME }}.jar
          asset_content_type: application/java-archive
