name: Release Candidate Build

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    outputs:
      version:
        description: Updated version for new release
        value: ${{ jobs.build_release_candidate.outputs.version }}


permissions:
  contents: write

jobs:
  build_release_candidate:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-${{ github.sha }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract configuration
        id: environment
        uses: actions/github-script@v6
        with:
          script: |
            const environment = '${{ inputs.environment }}';
            console.log("Environment: " + environment);
            try {
              const parsed = JSON.parse(environment);
              console.log('Parsed: ' + parsed);
              for(let key in parsed) {
                if (parsed.hasOwnProperty(key)) {
                  console.log(key + ': ' + parsed[key]);
                  core.exportVariable(key, parsed[key]);
                }
              }
            } catch (error) {
              console.error("Error parsing JSON:", error);
              core.setFailed(error.message);
            }


      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java_version }}
          distribution: ${{ env.java_distribution }}
          cache: ${{ env.java_cache }}

      - name: Bump version
        if: ${{ inputs.configuration.bump_version != false }}
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1
        with:
          pom-file: 'pom.xml'
          bump-command: 'mvn versions:set -DnewVersion=@NEW_VERSION@'

      - name: Build release candidate
        run: mvn clean package

      - name: Update version
        id: version
        run: | 
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-candidate-jar
          path: target/

