name: "Unit Test Action"

on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    outputs:
      test-result:
        description: "Result of Unit Testing"
        value: ${{ jobs.test.outputs.outcome }}

jobs:
  test:
    name: Run Standard Unit Tests
    runs-on: ubuntu-latest

    outputs:
      outcome: ${{steps.status.outcome}}
    steps:
      - name: Restore repository cache
        uses: actions/cache@v4
        with:
          path: .
          key: ${{ runner.os }}-repo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-repo-${{ github.sha }}

      - name: Extract Environment
        id: environment
        uses: actions/github-script@v6
        with:
          script: |
            const environment = '${{ inputs.configuration }}';
            console.log("Environment: " + environment);
            try {
              const parsed = JSON.parse(environment);
              console.log('Parsed: ' + parsed);
              for(let key in parsed) {
                if (parsed.hasOwnProperty(key)) {
                  console.log(key + ': ' + parsed[key]);
                  core.exportVariable(key, parsed[key]);
                }
              }
            } catch (error) {
              console.error("Error parsing JSON:", error);
              core.setFailed(error.message);
            }

      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java_version }}
          distribution: ${{ env.java_distribution }}
          cache: ${{ env.java_cache }}


      - name: Restore Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run unit tests
        id: run-test
        run: |
          mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ./target/site/jacoco/index.html

      - name: Set status
        id: status
        run: |
          echo "TESTS_PASSED=true" >> $GITHUB_ENV
          echo "TESTS_PASSED=true" >> $GITHUB_OUTPUT
          echo "outcome=true" >> $GITHUB_OUTPUT

